spring:
  application:
    name: java-spring-day2-service
  rabbitmq:
    addresses: localhost
    virtualhost: /
    port: 15672
    username: guest
    password: guest
    exchange: java-spring-boot-day2.exchange
    queue: java-spring-boot-day2.queue
    routingkey: java-spring-boot-day2.routingkey

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_db
    username: postgres
    password: root

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  # Logger configuration
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
      org.springframework: INFO

server:
  port : 7070
